# Generated by Django 4.2.6 on 2023-10-20 16:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_carcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='cat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.carcategory'),
        ),
    ]
