# Generated by Django 4.2.6 on 2023-10-20 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_car_cat'),
    ]

    operations = [
        migrations.CreateModel(
            name='Masters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name of repairman')),
            ],
            options={
                'verbose_name': 'Repairman',
                'verbose_name_plural': 'Repairmen',
                'ordering': ('name',),
            },
        ),
    ]
