# Generated by Django 4.2.6 on 2023-10-20 17:33

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_carimages'),
    ]

    operations = [
        migrations.AddField(
            model_name='carcategory',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='myapp.carcategory'),
        ),
        migrations.AlterField(
            model_name='carcategory',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
